default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'watch_shop_dev'

test:
  <<: *default
  database: 'watch_shop_test'

production:
  <<: *default
  database: 'watch_shop_prod'
